# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
    provider: kubernetes
  name: logger
  namespace: default
spec:
  ports:
  - name: logger
    port: 10001
    protocol: UDP
    targetPort: 10001
  type: ClusterIP
  selector:
    app: logger
---
apiVersion: v1
kind: Pod
metadata:
  name: udpserver
  labels:
    app: logger
spec:
  restartPolicy: Always
  containers:
  - name: udpserver
    image: "girishkalele/udpserver:1.0"
    imagePullPolicy: Always
    ports:
        - name: logger
          protocol: UDP
          containerPort: 10001

---
apiVersion: v1
kind: Pod
metadata:
  name: udpclient
  labels:
    app: loggerclient
spec:
  restartPolicy: Always
  containers:
  - name: udpclient
    imagePullPolicy: Always
    image: "girishkalele/udpclient:1.0"

